import { useState } from 'react'
import students from '../../data/applications.json'
import { getRecords } from '../../services/internshipRecordService'
import { getReports, reviewReport } from '../../services/reportService'
import { saveEvaluation } from '../../services/evaluationService'

function Shell({ title, description, children }) { return <section><div className="dashboard-page-heading"><div><p className="dashboard-eyebrow">KHU VỰC GIẢNG VIÊN</p><h1>{title}</h1><p>{description}</p></div><span className="dashboard-chip">Học kỳ 2 - 2024/2025</span></div>{children}</section> }
export function LecturerStudentsPage() { const records = getRecords().filter((record) => record.lecturer); const rows = records.length ? records.map((record) => ({ name: 'Nguyễn Minh Anh', internship: record.position, status: record.status })) : students.map((x) => ({ name: 'Nguyễn Minh Anh', internship: `Hồ sơ #${x.id}`, status: x.statusLabel })); return <Shell title="Sinh viên được phân công" description="Danh sách sinh viên thuộc phạm vi hướng dẫn của bạn."><Table rows={rows} /></Shell> }
export function LecturerInternshipsPage() { const rows = [{ name: 'Nguyễn Minh Anh', code: 'SV001234', className: 'KTPM2022', company: 'FPT Software', progress: 80, status: 'Đúng tiến độ' }, { name: 'Lê Thùy Linh', code: 'SV001235', className: 'HTTT2022', company: 'Viettel Solutions', progress: 60, status: 'Cần lưu ý' }, { name: 'Phạm Gia Hân', code: 'SV001238', className: 'TMĐT2022', company: 'Shopee', progress: 30, status: 'Nguy cơ trễ' }]; return <Shell title="Theo dõi tiến độ thực tập" description="Theo dõi quá trình thực tập của sinh viên được phân công."><div className="mb-4 grid gap-3 sm:grid-cols-4">{[['Tổng sinh viên', '24'], ['Đang tiến độ', '18'], ['Cần lưu ý', '4'], ['Nguy cơ trễ', '2']].map(([label, value]) => <div className="rounded-xl border border-[#e1eaf5] bg-white p-4" key={label}><p className="text-xs text-[#7890ad]">{label}</p><strong className="mt-2 block text-2xl text-[#0757c9]">{value}</strong></div>)}</div><div className="overflow-x-auto rounded-xl border border-[#e1eaf5] bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-[#f5f8fc] text-xs text-[#7890ad]"><tr><th className="p-4">Sinh viên</th><th className="p-4">Lớp</th><th className="p-4">Doanh nghiệp</th><th className="p-4">Tiến độ</th><th className="p-4">Trạng thái</th><th className="p-4">Thao tác</th></tr></thead><tbody>{rows.map((row) => <tr className="border-t border-[#edf1f6]" key={row.code}><td className="p-4 font-semibold text-[#173b83]">{row.name}<small className="block font-normal text-[#7890ad]">{row.code}</small></td><td className="p-4 text-[#526b8d]">{row.className}</td><td className="p-4 text-[#526b8d]">{row.company}</td><td className="p-4"><b className="text-[#0757c9]">{row.progress}%</b><div className="mt-2 h-1.5 w-28 rounded-full bg-[#e5eef8]"><div className={`h-full rounded-full ${row.progress < 50 ? 'w-1/3 bg-red-400' : 'w-3/4 bg-[#0aa46e]'}`} /></div></td><td className="p-4"><span className={`status-badge ${row.progress < 50 ? 'warning' : 'success'}`}>{row.status}</span></td><td className="p-4"><button className="rounded-md border border-[#bcd3ec] px-3 py-2 text-xs font-bold text-[#0757c9]" type="button">Xem hồ sơ</button></td></tr>)}</tbody></table></div></Shell> }
export function LecturerDiariesPage() { const [comment, setComment] = useState(''); const [saved, setSaved] = useState(false); return <Shell title="Nhật ký thực tập" description="Xem nhật ký và ghi nhận nhận xét trong kỳ."><div className="rounded-xl border border-[#e1eaf5] bg-white p-5"><p className="text-xs font-bold text-[#7890ad]">Nguyễn Minh Anh · Tuần 1</p><p className="mt-2 text-sm text-[#2b4263]">Hoàn thành thiết kế giao diện trang danh sách cơ hội.</p><textarea className="mt-4 w-full rounded-md border border-[#d8e3f0] p-3 text-sm" placeholder="Nhập nhận xét..." value={comment} onChange={(e) => setComment(e.target.value)} />{saved && <p className="mt-2 text-sm font-semibold text-green-600">Đã lưu nhận xét.</p>}<button onClick={() => setSaved(true)} className="mt-3 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white" type="button">Lưu nhận xét</button></div></Shell> }
export function LecturerReportsPage() { const [reports, setReports] = useState(getReports()); function review(id, approved) { setReports(reviewReport(id, approved, approved ? 'Báo cáo đạt yêu cầu.' : 'Vui lòng bổ sung nội dung và minh chứng.')) } return <Shell title="Báo cáo cần duyệt" description="Kiểm tra và phản hồi báo cáo tổng kết của sinh viên."><div className="space-y-3">{reports.length ? reports.map((report) => <article className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-[#e1eaf5] bg-white p-5" key={report.id}><div><h2 className="font-bold text-[#173b83]">{report.name}</h2><p className="mt-1 text-xs text-[#7890ad]">Sinh viên: Nguyễn Minh Anh · Phiên bản {report.version}</p></div><div className="flex gap-2"><button disabled={report.status !== 'Chờ giảng viên duyệt'} className="rounded-md border border-red-200 px-3 py-2 text-xs font-bold text-red-600 disabled:opacity-40" type="button" onClick={() => review(report.id, false)}>Yêu cầu sửa</button><button disabled={report.status !== 'Chờ giảng viên duyệt'} className="rounded-md bg-[#0aa46e] px-3 py-2 text-xs font-bold text-white disabled:opacity-40" type="button" onClick={() => review(report.id, true)}>Phê duyệt</button></div></article>) : <Empty text="Chưa có báo cáo chờ duyệt." />}</div></Shell> }
export function LecturerEvaluationsPage() { const [score, setScore] = useState(''); const [saved, setSaved] = useState(false); function save() { saveEvaluation({ studentId: 1, evaluatorRole: 'lecturer', score }); setSaved(true) } return <Shell title="Đánh giá cuối kỳ" description="Chấm điểm và ký xác nhận kết quả thực tập."><div className="max-w-xl rounded-xl border border-[#e1eaf5] bg-white p-5"><p className="font-bold text-[#172d50]">Nguyễn Minh Anh</p><label className="mt-5 block text-sm font-semibold text-[#2b4263]">Điểm tổng kết<input type="number" min="0" max="10" value={score} onChange={(e) => { setScore(e.target.value); setSaved(false) }} className="mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-2.5" /></label><button disabled={!score} onClick={save} className="mt-4 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white disabled:bg-slate-300" type="button">Gửi đánh giá</button>{saved && <p className="mt-3 text-sm font-semibold text-green-600">Đánh giá đã được lưu và không thể sửa.</p>}</div></Shell> }
function Table({ rows }) { return <div className="overflow-x-auto rounded-xl border border-[#e1eaf5] bg-white"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-[#f5f8fc] text-xs uppercase text-[#7890ad]"><tr><th className="p-4">Sinh viên</th><th className="p-4">Hồ sơ</th><th className="p-4">Trạng thái</th></tr></thead><tbody>{rows.map((row, index) => <tr className="border-t border-[#edf1f6]" key={index}><td className="p-4 font-semibold text-[#172d50]">{row.name}</td><td className="p-4 text-[#526b8d]">{row.internship}</td><td className="p-4 text-[#0757c9]">{row.status}</td></tr>)}</tbody></table></div> }
function Empty({ text }) { return <div className="rounded-xl border border-dashed border-[#b9cee8] bg-white p-10 text-center text-sm text-[#7890ad]">{text}</div> }
