import { useState } from 'react'
import internships from '../../data/internships.json'
import { INTERNSHIP_STATUSES } from '../../constants/internshipStatuses'
import StatusBadge from '../../components/ui/StatusBadge'
import { confirmOffer, getInterviews, respondInterview } from '../../services/interviewService'
import { createRecord, getRecords } from '../../services/internshipRecordService'
import { getReports, submitReport } from '../../services/reportService'
import { applyForInternship, getApplications, getStudent, saveStudent } from '../../services/studentService'

const key = 'internconnect_student_notes'
function readNotes() { try { return JSON.parse(localStorage.getItem(key)) || [] } catch { return [] } }
function saveNotes(notes) { localStorage.setItem(key, JSON.stringify(notes)); return notes }

export function StudentProfilePage() {
  const [student, setStudent] = useState(getStudent()); const [saved, setSaved] = useState(false)
  function submit(e) { e.preventDefault(); saveStudent(student); setSaved(true) }
  return <Page title="Hồ sơ cá nhân & CV" description="Quản lý thông tin dùng trong quá trình ứng tuyển."><form onSubmit={submit} className="rounded-xl border border-[#e1eaf5] bg-white p-6"><div className="grid gap-4 md:grid-cols-2">{[['fullName','Họ và tên'],['email','Email'],['phone','Số điện thoại'],['major','Chuyên ngành'],['className','Lớp']].map(([field,label]) => <label className="text-sm font-semibold text-[#2b4263]" key={field}>{label}<input value={student[field]} onChange={(e) => setStudent({ ...student, [field]: e.target.value })} className="mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-2.5 font-normal" /></label>)}</div><label className="mt-4 block text-sm font-semibold text-[#2b4263]">Kỹ năng<input value={student.skills.join(', ')} onChange={(e) => setStudent({ ...student, skills: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })} className="mt-2 w-full rounded-md border border-[#d8e3f0] px-3 py-2.5 font-normal" /></label><div className="mt-5 rounded-lg bg-[#edf4ff] p-4 text-sm text-[#4774b3]"><b>CV mặc định:</b> {student.cv.name}<br /><span className="text-xs">Hỗ trợ PDF/DOCX sẽ được nối storage backend ở giai đoạn sau.</span></div>{saved && <p className="mt-4 text-sm font-semibold text-green-600">Đã lưu hồ sơ.</p>}<button className="mt-5 rounded-md bg-[#0757c9] px-5 py-3 text-sm font-bold text-white" type="submit">Lưu thay đổi</button></form></Page>
}

export function StudentOpportunitiesPage() {
  const [query, setQuery] = useState(''); const [applications, setApplications] = useState(getApplications()); const [message, setMessage] = useState('')
  const items = internships.filter((item) => `${item.company} ${item.position} ${item.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())); const applied = new Set(applications.map((x) => x.internshipId))
  function apply(id) { setApplications(applyForInternship(id)); setMessage('Đã gửi hồ sơ ứng tuyển.') }
  return <Page title="Cơ hội thực tập" description="Tìm kiếm và ứng tuyển các vị trí phù hợp."><input className="mb-5 w-full rounded-lg border border-[#d8e3f0] bg-white px-4 py-3 text-sm" placeholder="Tìm công ty, vị trí hoặc kỹ năng..." value={query} onChange={(e) => setQuery(e.target.value)} />{message && <p className="mb-4 text-sm font-semibold text-green-600">{message}</p>}<div className="grid gap-4 md:grid-cols-2">{items.map((item) => <article className="rounded-xl border border-[#e1eaf5] bg-white p-5" key={item.id}><p className="text-xs text-[#7890ad]">{item.company} · {item.location}</p><h2 className="mt-2 font-bold text-[#172d50]">{item.position}</h2><div className="mt-3 flex flex-wrap gap-2">{item.tags.map((tag) => <span className="rounded-full bg-[#edf4ff] px-2 py-1 text-xs text-[#4774b3]" key={tag}>{tag}</span>)}</div><button type="button" onClick={() => apply(item.id)} disabled={applied.has(item.id)} className="mt-5 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white disabled:bg-slate-300">{applied.has(item.id) ? 'Đã ứng tuyển' : 'Ứng tuyển ngay'}</button></article>)}</div></Page>
}

export function StudentApplicationsPage() { const [apps, setApps] = useState(getApplications()); function offer(id, accepted) { setApps(confirmOffer(id, accepted)) } return <Page title="Quản lý ứng tuyển" description="Theo dõi toàn bộ hồ sơ và lịch sử xử lý."><div className="space-y-4">{apps.map((app) => { const item = internships.find((x) => x.id === app.internshipId); const current = INTERNSHIP_STATUSES.findIndex((x) => x.id === app.status); const canConfirm = app.status === '09' && app.statusLabel === 'Trúng tuyển'; return <article className="rounded-xl border border-[#e1eaf5] bg-white p-5" key={app.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-[#173b83]">{item?.position} · {item?.company}</h2><p className="mt-1 text-xs text-[#7890ad]">Mã hồ sơ: #{app.id} · Cập nhật theo từng mốc nghiệp vụ</p></div><StatusBadge status={app.status} /></div>{canConfirm && <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-green-50 p-4"><p className="text-sm font-semibold text-green-700">Bạn đã trúng tuyển. Xác nhận nhận thực tập để chuyển sang bước tiếp theo.</p><div className="flex gap-2"><button className="rounded-md border border-red-200 px-3 py-2 text-xs font-bold text-red-600" type="button" onClick={() => offer(app.id, false)}>Từ chối</button><button className="rounded-md bg-[#0aa46e] px-3 py-2 text-xs font-bold text-white" type="button" onClick={() => offer(app.id, true)}>Nhận thực tập</button></div></div>}<div className="mt-4 flex flex-wrap gap-2">{INTERNSHIP_STATUSES.map((status, index) => <span className={`rounded-md px-2 py-1 text-[11px] ${index <= current ? 'bg-[#dcecff] font-bold text-[#0757c9]' : 'bg-slate-100 text-slate-400'}`} key={status.id}>{status.id}. {status.label}</span>)}</div></article>})}</div></Page> }

export function StudentInterviewsPage() { const [interviews, setInterviews] = useState(getInterviews()); function respond(id, accepted) { setInterviews(respondInterview(id, accepted)) } return <Page title="Lịch phỏng vấn" description="Theo dõi và xác nhận lịch phỏng vấn do doanh nghiệp gửi."><div className="space-y-4">{interviews.length ? interviews.map((interview) => <article className="flex flex-wrap items-center justify-between gap-5 rounded-xl border border-[#e1eaf5] bg-white p-5" key={interview.id}><div><p className="text-xs font-bold text-[#7890ad]">{interview.date} · {interview.time}</p><h2 className="mt-2 font-bold text-[#173b83]">Frontend Developer Intern</h2><p className="mt-1 text-sm text-[#526f94]">FPT Software · {interview.mode} · {interview.location}</p></div><div className="flex items-center gap-2">{interview.status === 'Chờ sinh viên xác nhận' ? <><button className="rounded-md border border-red-200 px-3 py-2 text-xs font-bold text-red-600" type="button" onClick={() => respond(interview.id, false)}>Từ chối</button><button className="rounded-md bg-[#0757c9] px-3 py-2 text-xs font-bold text-white" type="button" onClick={() => respond(interview.id, true)}>Xác nhận lịch</button></> : <span className="status-badge info">{interview.status}</span>}</div></article>) : <Empty title="Chưa có lịch phỏng vấn" text="Khi doanh nghiệp mời phỏng vấn, lịch sẽ hiển thị tại đây." />}</div></Page> }
export function StudentInternshipPage() { const [records, setRecords] = useState(getRecords()); const application = getApplications().find((item) => item.status === '11'); function create() { if (application) setRecords(createRecord(application)) } return <Page title="Hồ sơ thực tập" description="Theo dõi doanh nghiệp, giảng viên hướng dẫn và tiến độ thực tập."><div className="space-y-4">{records.map((record) => <article className="rounded-xl border border-[#e1eaf5] bg-white p-6" key={record.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-[#7890ad]">{record.period}</p><h2 className="mt-2 text-xl font-bold text-[#173b83]">{record.position}</h2><p className="mt-1 text-sm text-[#526f94]">{record.company} · GV hướng dẫn: {record.lecturer || 'Chờ phân công'}</p></div><StatusBadge label={record.status} status={record.status === 'Đang thực tập' ? '13' : '12'} /></div></article>)}{!records.length && application && <div className="rounded-xl border border-[#b9d8f4] bg-white p-6"><h2 className="font-bold text-[#173b83]">Bạn đã xác nhận nhận thực tập</h2><p className="mt-2 text-sm text-[#7890ad]">Hãy tạo hồ sơ thực tập để nhà trường xác nhận kỳ và nơi thực tập.</p><button type="button" onClick={create} className="mt-4 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white">Tạo hồ sơ thực tập</button></div>}{!records.length && !application && <Empty title="Chưa có hồ sơ thực tập" text="Hồ sơ sẽ được tạo sau khi bạn xác nhận nhận offer." />}</div></Page> }
export function StudentDiaryPage() { const [notes, setNotes] = useState(readNotes()); const [text, setText] = useState(''); const active = getRecords().some((record) => record.status === 'Đang thực tập'); function add(e) { e.preventDefault(); if (!text.trim()) return; setNotes(saveNotes([{ id: Date.now(), date: new Date().toLocaleDateString('vi-VN'), text }, ...notes])); setText('') } return <Page title="Nhật ký thực tập" description="Ghi nhận công việc và nhận xét trong quá trình thực tập.">{active ? <><form onSubmit={add} className="rounded-xl border border-[#e1eaf5] bg-white p-5"><textarea required className="min-h-32 w-full rounded-md border border-[#d8e3f0] p-3 text-sm" placeholder="Nhập nội dung nhật ký..." value={text} onChange={(e) => setText(e.target.value)} /><button className="mt-3 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white" type="submit">Lưu nhật ký</button></form><div className="mt-5 space-y-3">{notes.map((note) => <article className="rounded-lg border border-[#e1eaf5] bg-white p-4" key={note.id}><p className="text-xs font-bold text-[#7890ad]">{note.date}</p><p className="mt-2 text-sm text-[#2b4263]">{note.text}</p></article>)}</div></> : <Empty title="Chưa thể ghi nhật ký" text="Bạn chỉ có thể ghi nhật ký sau khi nhà trường xác nhận và chuyển hồ sơ sang trạng thái đang thực tập." />}</Page> }
export function StudentReportsPage() { const [reports, setReports] = useState(getReports()); const [fileName, setFileName] = useState(''); function submit(event) { event.preventDefault(); if (!fileName) return; setReports(submitReport({ studentId: 1, name: fileName, version: reports.length + 1 })) } return <Page title="Báo cáo thực tập" description="Nộp báo cáo tổng kết và theo dõi phản hồi từ giảng viên."><form onSubmit={submit} className="rounded-xl border border-[#e1eaf5] bg-white p-6"><h2 className="font-bold text-[#173b83]">Tải lên báo cáo</h2><p className="mt-2 text-sm text-[#7890ad]">Định dạng PDF/DOCX, tối đa 20MB.</p><input className="mt-5 block w-full rounded-md border border-[#d8e3f0] p-3 text-sm" type="file" accept=".pdf,.doc,.docx" onChange={(e) => setFileName(e.target.files?.[0]?.name || '')} /><button className="mt-4 rounded-md bg-[#0757c9] px-4 py-2 text-sm font-bold text-white disabled:bg-slate-300" disabled={!fileName} type="submit">Nộp báo cáo</button></form><div className="mt-5 space-y-3">{reports.map((report) => <article className="flex flex-wrap justify-between gap-3 rounded-xl border border-[#e1eaf5] bg-white p-5" key={report.id}><div><h3 className="font-bold text-[#173b83]">{report.name}</h3><p className="mt-1 text-xs text-[#7890ad]">Phiên bản {report.version}</p></div><span className="status-badge info">{report.status}</span></article>)}</div></Page> }

function Page({ title, description, children }) { return <section><div className="dashboard-page-heading"><div><p className="dashboard-eyebrow">KHU VỰC SINH VIÊN</p><h1>{title}</h1><p>{description}</p></div><span className="dashboard-chip">Đã đồng bộ</span></div>{children}</section> }
function Empty({ title, text }) { return <div className="rounded-xl border border-dashed border-[#b9cee8] bg-white p-10 text-center"><h2 className="font-bold text-[#172d50]">{title}</h2><p className="mt-2 text-sm text-[#7890ad]">{text}</p></div> }
